### ISSUE TITLE
same size icon for on and off lights ?

### ISSUE THREAD

**Issue by mattcasper** [michael5r/mmm-hue-lights#10]
![capture d ecran 2019-02-21 a 6 03 20 pm](https://user-images.githubusercontent.com/47028081/53187622-d651d600-3603-11e9-9856-e57f55a4dcf4.png)

hello
thanks for this great module,
is it possible to disable the dimming status bar under the lights that are on?
i would like to have the icon of the lights on the same size as the lights off, the only indicator would be the change in color.

any help would be highly appreciated
best [regards](url)

**Comment by michael5r** [comment]
Sure - just add this to your `custom.css` file in magic mirror:

```css
.mmm-hue-lights .grid .hue .bot {
    display: none;
}
```

**Comment by mattcasper** [comment]
amazing, thanks a lot!!
![capture d ecran 2019-02-21 a 6 28 13 pm](https://user-images.githubusercontent.com/47028081/53188885-8de7e780-3606-11e9-886b-f0c0fb9a1782.png)


it doesn't seem to work with just the mouse but do you know if i could toggle on&off the lights with a touchscreen?

**Comment by michael5r** [comment]
@mattcasper No, this module only displays the light status - you can't interact with them, unfortunately. I personally just use google voice to control them through my mirror ...

**Comment by mattcasper** [comment]
should i use the same .mmm-hue-lights .grid .hue .bot to reduce the size on the icons and their opacity?

**Comment by michael5r** [comment]
If you're talking about the small light bulb icon on the left side, it's:
```css
.mmm-hue-lights .grid .hue .icn {
    width: 15px;
    height: 20px;
}
```

The icon for groups is larger, so that's:
```css
.mmm-hue-lights .grid.groups .hue .icn {
    width: 27px;
    height: 26px;
}
```

You can add an `opacity` style to either of those to make them more transparent.

**Comment by mattcasper** [comment]
i meant the size of those box
![capture d ecran 2019-02-21 a 9 59 24 pm](https://user-images.githubusercontent.com/47028081/53201331-07420300-3624-11e9-983f-492998bd7a90.png)
the 2nd solution doesn't seem to work and  the .mmm-hue-lights .grid .hue .bot neither

**Comment by michael5r** [comment]
Ahh, I see. If you're talking about the width of those elements, it's this:
```css
.mmm-hue-lights .grid {
    max-width: 300px;
}
```
You can change the `max-width` to whatever you prefer.

If you wish to change the opacity of each light element, it's this:
```css
.mmm-hue-lights .grid .hue {
    // set opacity here
}
```
There's no easy way to change the height, unfortunately - it, of course, can be done, but it would require you to change the height of multiple elements to make sure they line up nicely.
